In [49]:
import sys
import os
sys.path.append(os.path.abspath("/Users/jcaledo/Py_pkgs/POFF/src"))
import numpy as np
import row_echelon_form as ref
import Zmod as zm

In [48]:
%reset -f


In [50]:
M = np.array([[ 2, -2,  4, -2],
                  [ 2,  1, 10,  7],
                  [-4,  4, -8,  4],
                  [4, -1, 14,  6]])

A = M.copy()
ref.make_pivot_one(A, 0, 0, mod = 3)
print(A)

[[ 4 -4  8 -4]
 [ 2  1 10  7]
 [-4  4 -8  4]
 [ 4 -1 14  6]]
