In [1]:
import sys
import numpy as np
import Zmod as zm

In [6]:
def find_nonzero_row(matrix, pivot_row, col): 
    nrows = matrix.shape[0] 
    for row in range(pivot_row, nrows):
        if matrix[row, col] != 0: 
            return row 
    return None

In [7]:
def swap_rows(matrix, row1, row2):
    matrix[row1], matrix[row2] = matrix[row2], matrix[row1]

In [33]:
def make_pivot_one(matrix, pivot_row, col, mod = None):
    """_summary_

    Args:
        matrix (_type_): _description_
        pivot_row (_type_): _description_
        col (_type_): _description_
        mod (_type_, optional): _description_. Defaults to None.
    """
    if mod == None:
        pivot = matrix[pivot_row, col]
        matrix[pivot_row] //= pivot
    elif type(mod) is int:
        pivot_inv = zm.get_inv(matrix[pivot_row, col], mod)
        matrix[pivot_row] *= pivot_inv
        matrix[pivot_row] = matrix[pivot_row] % mod
    else:
        sys.exit("The mod should be a positive integer")

In [34]:
A = matrix = np.array([[ 2, -2,  4, -2],
       [ 2,  1, 10,  7],
       [-4,  4, -8,  4],
       [ 4, -1, 14,  6]])

B= zm.get_canonical(A, 3)
make_pivot_one(B, 0, 0, 3)

print(B)


[[1 2 2 2]
 [2 1 1 1]
 [2 1 1 1]
 [1 2 2 0]]


In [10]:
def make_zero_below(matrix, pivot_row, col, mod = None):
    """_summary_

    Args:
        matrix (_type_): _description_
        pivot_row (_type_): _description_
        col (_type_): _description_
        mod (_type_, optional): _description_. Defaults to None.
    """
    nrow = matrix.shape[0]
    for row in range(pivot_row + 1, nrow):
        factor = matrix[row, col]
        matrix[row] -= factor * matrix[pivot_row]

In [11]:
M = np.array([[ 2, -2,  4, -2],
       [ 2,  1, 10,  7],
       [-4,  4, -8,  4],
       [ 4, -1, 14,  6]])

In [12]:
print(M)

[[ 2 -2  4 -2]
 [ 2  1 10  7]
 [-4  4 -8  4]
 [ 4 -1 14  6]]
